name: 合并结果文件

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  merge_results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码库
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: 安装依赖
        run: npm install

      - name: 合并结果文件
        run: node mergeResults.js

      - name: 复制文件到结果目录
        run: |
          
          cp data/* result/

      - name: 提交更改到主分支
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add result/*
          git commit -m "Add merged result files"
          git push
