name: fetch-website-content

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 23 * * *'

jobs:
  fetch-website-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码库
        uses: actions/checkout@v3

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: 安装依赖
        run: npm install puppeteer moment

      - name: 爬取网页
        id: fetch-webpage
        run: |
          urls=$(cat urls)
          for url in $urls; do
            filename=$(echo "$url" | awk -F/ '{ print $3 }')
            timestamp=$(date +'%Y%m%d%H%M%S')
            filepath="data/${filename}_${timestamp}.txt"
            node read_website.js "$url" "$filepath"
          done

      - name: 设置 Git 配置
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: 提交文件到主分支
        run: |
          git add data
          git commit -m 'Add website content'
          git push origin HEAD:main
